# Generated by Django 4.1.3 on 2023-02-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0002_checkkoutdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkkoutdb',
            name='Scdaddres',
        ),
    ]
