# Generated by Django 4.1.3 on 2023-01-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backent', '0002_addcategorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='producpagedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Prize', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
